#index:
#    path: /
#    controller: App\Controller\DefaultController::index

any_name:
    path: /api/admin
    methods: GET
    controller: App\Controller\DefaultController::admin_1

gen_user:
    path: /api/genUserWithIpLog
    methods: POST
    controller: App\Controller\DefaultController::genUser

create_user_api:
    path: /api/user
    methods: POST
    controller: App\Controller\UserController::createUser

show_form_add_new_user:
    path: /api/user/new
    methods: POST
    controller: App\Controller\UserController::showFormAddNewUser


show_user_by_id:
    path: /api/user/{id}/show
    methods: POST
    controller: App\Controller\DefaultController::showById

show_user_info_by_id:
    path: /api/user/{id}/show-info/{page}
    methods: [GET,POST]
    controller: App\Controller\UserController::showUserInfoById

gen_comment_by_id:
    path: /api/user/{id}/gen-comment
    methods: POST
    controller: App\Controller\DefaultController::genComment

add_comment_by_id:
    path: /api/user/{id}/add-comment
    methods: POST
    controller: App\Controller\UserController::addComment

show_form_add_comment_by_id:
    path: /api/user/{id}/form-add-comment
    methods: POST
    controller: App\Controller\UserController::showFormAddComment

delete_user_by_id:
    path: /api/user/{id}
    methods: [DELETE, POST]
    controller: App\Controller\DefaultController::deleteById

any_my_name_6:
    path: /index
    methods: GET
    controller: App\Controller\DefaultController::index

any_my_name_7:
    path: /add
    methods: GET
    controller: App\Controller\DefaultController::addUser

show_articles:
    path: /api/showArticles
    methods: GET
    controller: App\Controller\DefaultController::showArticles

show_users:
    path: /api/showUsers
    methods: GET
    controller: App\Controller\DefaultController::showUsers

show_comments_by_id:
    path: /api/comments/{id}/show/{page}
    methods: [GET,POST]
    controller: App\Controller\ArticleController::showCommentsById

login:
    path: /login
    methods: [GET,POST]
    controller: App\Controller\Defaultcontroller::login
logout:
    path: /index
    methods: [GET,POST]
    controller: App\Controller\Defaultcontroller::index

#createUser:
#    path: /create-user
#    controller: App\Controller\DefaultController::createUser

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }